# Generated by Django 3.2 on 2025-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
